### ISSUE TITLE
Upgrade deps

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [bacongravy/emoji-favicon-cli#7]
Would it be possible to upgrade the dependencies? In particular `meow`. I can send a PR.

**Comment by bacongravy** [comment]
Dependencies were updated with [this commit](https://github.com/bacongravy/emoji-favicon-cli/commit/b45add40f1ce32d1e43a75d7e87dcf5961c92851) and released in v3.0.1, which has been published to NPM.

**Comment by make-github-pseudonymous-again** [comment]
@bacongravy Thanks a lot!
